services:
  studygroups_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: studygroups-api
    image: hse.devsec.studygroups:${STUDYGROUPD_API_TAG}
    restart: unless-stopped

    # Запрект повышения привелегий и модуль безопасности ядра Limix - AppArmor, блокировка системных вызовов seccomp
    security_opt:
      - no-new-privileges:true
      - apparmor:docker-default
    # Ограничение возможных прав пользователя внутри контейнера
    cap_drop:
      - ALL
    depends_on:
      studygroups_db:
        condition: service_healthy
        restart: true
    env_file:
      - ./.env
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - hse-devsec-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 20s

  studygroups_db:
    image: postgres:17-alpine
    container_name: studygroups-db
    restart: unless-stopped
    shm_size: 128mb
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_SYS_USER}
      POSTGRES_PASSWORD: ${PG_SYS_PSWD}
    volumes:
      - hse-devsec-pg-data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    networks:
      - hse-devsec-network
    ports:
      - ${PG_EXP_PORT:-5432}:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${PG_SYS_USER}", "-d", "${PG_DB}"]
      interval: 10s
      retries: 3
      start_period: 15s
      timeout: 10s

  studygroups_api_gateway:
    image: nginx:1.28-alpine
    volumes:
      - ./gateway/nginx.conf.template:/etc/nginx/templates/default.conf.template
    environment:
      - AUTH_API_URL=${SECDEV_GA_AUTH_URL}
    ports:
      - ${SD_AA_GATEWAY_PORT:-80}:80
    networks:
      - hse-devsec-network

volumes:
  hse-devsec-pg-data:
    driver: local

networks:
  hse-devsec-network:
    driver: bridge
